<dec f='glibc_src_2.30/posix/spawn_int.h' l='63' type='union (anonymous union at /home/fp/glibc/glibc_src/argp/../posix/spawn_int.h:37:3)'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='207' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='216' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='217' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='230' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='232' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='233' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='235' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='243' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='245' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='246' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='258' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='259' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='261' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='268' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='269' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='270' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='275' u='m' c='__spawni_child'/>
<use f='glibc_src_2.30/sysdeps/unix/sysv/linux/spawni.c' l='280' u='m' c='__spawni_child'/>
<offset>64</offset>
<use f='glibc_src_2.30/posix/spawn_faction_addchdir.c' l='47' u='m' c='posix_spawn_file_actions_addchdir_np'/>
<use f='glibc_src_2.30/posix/spawn_faction_addclose.c' l='44' u='m' c='__posix_spawn_file_actions_addclose'/>
<use f='glibc_src_2.30/posix/spawn_faction_adddup2.c' l='44' u='m' c='__posix_spawn_file_actions_adddup2'/>
<use f='glibc_src_2.30/posix/spawn_faction_adddup2.c' l='45' u='m' c='__posix_spawn_file_actions_adddup2'/>
<use f='glibc_src_2.30/posix/spawn_faction_addfchdir.c' l='40' u='m' c='posix_spawn_file_actions_addfchdir_np'/>
<use f='glibc_src_2.30/posix/spawn_faction_addopen.c' l='53' u='m' c='posix_spawn_file_actions_addopen'/>
<use f='glibc_src_2.30/posix/spawn_faction_addopen.c' l='54' u='m' c='posix_spawn_file_actions_addopen'/>
<use f='glibc_src_2.30/posix/spawn_faction_addopen.c' l='55' u='m' c='posix_spawn_file_actions_addopen'/>
<use f='glibc_src_2.30/posix/spawn_faction_addopen.c' l='56' u='m' c='posix_spawn_file_actions_addopen'/>
<use f='glibc_src_2.30/posix/spawn_faction_destroy.c' l='34' u='m' c='__posix_spawn_file_actions_destroy'/>
<use f='glibc_src_2.30/posix/spawn_faction_destroy.c' l='37' u='m' c='__posix_spawn_file_actions_destroy'/>
