<dec f='glibc_src_2.30/argp/argp-fmtstream.h' l='93' type='char *'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.h' l='196' u='r' c='__argp_fmtstream_write'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.h' l='198' u='r' c='__argp_fmtstream_write'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.h' l='199' u='w' c='__argp_fmtstream_write'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.h' l='222' u='r' c='__argp_fmtstream_putc'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.h' l='223' u='w' c='__argp_fmtstream_putc'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.h' l='233' u='r' c='__argp_fmtstream_set_lmargin'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.h' l='245' u='r' c='__argp_fmtstream_set_rmargin'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.h' l='257' u='r' c='__argp_fmtstream_set_wmargin'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.h' l='268' u='r' c='__argp_fmtstream_point'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='81' u='w' c='__argp_make_fmtstream'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='100' u='r' c='__argp_fmtstream_free'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='103' u='r' c='__argp_fmtstream_free'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='128' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='136' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='140' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='141' u='w' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='162' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='183' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='201' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='203' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='204' u='w' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='215' u='w' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='276' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='279' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='282' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='333' u='w' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='343' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='351' u='r' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='359' u='r' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='360' u='r' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='364' u='r' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='366' u='w' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='371' u='w' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='373' u='r' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='392' u='w' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='414' u='r' c='__argp_fmtstream_printf'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='415' u='r' c='__argp_fmtstream_printf'/>
<use f='glibc_src_2.30/argp/argp-fmtstream.c' l='422' u='w' c='__argp_fmtstream_printf'/>
<offset>448</offset>
<doc f='glibc_src_2.30/argp/argp-fmtstream.h' l='93'>/* Current end of text in BUF. */</doc>
