<dec f='glibc_src_2.25/argp/argp-fmtstream.h' l='93' type='char *'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.h' l='196' u='r' c='__argp_fmtstream_write'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.h' l='198' u='r' c='__argp_fmtstream_write'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.h' l='199' u='w' c='__argp_fmtstream_write'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.h' l='222' u='r' c='__argp_fmtstream_putc'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.h' l='223' u='w' c='__argp_fmtstream_putc'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.h' l='233' u='r' c='__argp_fmtstream_set_lmargin'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.h' l='245' u='r' c='__argp_fmtstream_set_rmargin'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.h' l='257' u='r' c='__argp_fmtstream_set_wmargin'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.h' l='268' u='r' c='__argp_fmtstream_point'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='82' u='w' c='__argp_make_fmtstream'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='101' u='r' c='__argp_fmtstream_free'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='104' u='r' c='__argp_fmtstream_free'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='129' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='137' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='141' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='142' u='w' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='161' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='182' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='200' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='202' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='203' u='w' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='214' u='w' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='275' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='278' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='281' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='330' u='w' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='340' u='r' c='__argp_fmtstream_update'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='348' u='r' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='356' u='r' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='357' u='r' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='361' u='r' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='363' u='w' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='368' u='w' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='370' u='r' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='389' u='w' c='__argp_fmtstream_ensure'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='411' u='r' c='__argp_fmtstream_printf'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='412' u='r' c='__argp_fmtstream_printf'/>
<use f='glibc_src_2.25/argp/argp-fmtstream.c' l='419' u='w' c='__argp_fmtstream_printf'/>
<offset>448</offset>
<doc f='glibc_src_2.25/argp/argp-fmtstream.h' l='93'>/* Current end of text in BUF. */</doc>
