<dec f='glibc_src_2.24/posix/spawn_int.h' l='53' type='union (anonymous union at /home/fp/glibc/glibc_src/argp/../posix/spawn_int.h:35:3)'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='205' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='206' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='207' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='218' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='227' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='228' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='238' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='236' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='235' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='246' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='248' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='249' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='259' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='260' u='m' c='__spawni_child'/>
<use f='glibc_src_2.24/sysdeps/unix/sysv/linux/spawni.c' l='261' u='m' c='__spawni_child'/>
<offset>64</offset>
<use f='glibc_src_2.24/posix/spawn_faction_addclose.c' l='44' u='m' c='posix_spawn_file_actions_addclose'/>
<use f='glibc_src_2.24/posix/spawn_faction_adddup2.c' l='44' u='m' c='posix_spawn_file_actions_adddup2'/>
<use f='glibc_src_2.24/posix/spawn_faction_adddup2.c' l='45' u='m' c='posix_spawn_file_actions_adddup2'/>
<use f='glibc_src_2.24/posix/spawn_faction_addopen.c' l='53' u='m' c='posix_spawn_file_actions_addopen'/>
<use f='glibc_src_2.24/posix/spawn_faction_addopen.c' l='54' u='m' c='posix_spawn_file_actions_addopen'/>
<use f='glibc_src_2.24/posix/spawn_faction_addopen.c' l='55' u='m' c='posix_spawn_file_actions_addopen'/>
<use f='glibc_src_2.24/posix/spawn_faction_addopen.c' l='56' u='m' c='posix_spawn_file_actions_addopen'/>
<use f='glibc_src_2.24/posix/spawn_faction_destroy.c' l='34' u='m' c='posix_spawn_file_actions_destroy'/>
