<dec f='glibc_src_2.24/sunrpc/rpc_parse.h' l='146' type='struct_def'/>
<offset>0</offset>
<use f='glibc_src_2.24/sunrpc/rpc_cout.c' l='456' u='m' c='inline_struct'/>
<use f='glibc_src_2.24/sunrpc/rpc_cout.c' l='615' u='m' c='emit_struct'/>
<use f='glibc_src_2.24/sunrpc/rpc_cout.c' l='620' u='m' c='emit_struct'/>
<use f='glibc_src_2.24/sunrpc/rpc_cout.c' l='632' u='m' c='emit_struct'/>
<use f='glibc_src_2.24/sunrpc/rpc_cout.c' l='659' u='m' c='emit_struct'/>
<use f='glibc_src_2.24/sunrpc/rpc_cout.c' l='676' u='m' c='emit_struct'/>
<use f='glibc_src_2.24/sunrpc/rpc_hout.c' l='203' u='m' c='pstructdef'/>
<use f='glibc_src_2.24/sunrpc/rpc_parse.c' l='121' u='m' c='def_struct'/>
<use f='glibc_src_2.24/sunrpc/rpc_parse.c' l='155' u='m' c='def_program'/>
