<dec f='glibc_src_2.29/iconv/iconvconfig.h' l='59' type='struct extra_entry_module [0]'/>
<use f='glibc_src_2.29/iconv/gconv_cache.c' l='297' u='m' c='__gconv_lookup_cache'/>
<use f='glibc_src_2.29/iconv/gconv_cache.c' l='322' u='m' c='__gconv_lookup_cache'/>
<use f='glibc_src_2.29/iconv/gconv_cache.c' l='328' u='m' c='__gconv_lookup_cache'/>
<use f='glibc_src_2.29/iconv/gconv_cache.c' l='333' u='m' c='__gconv_lookup_cache'/>
<use f='glibc_src_2.29/iconv/gconv_cache.c' l='334' u='m' c='__gconv_lookup_cache'/>
<use f='glibc_src_2.29/iconv/gconv_cache.c' l='347' u='m' c='__gconv_lookup_cache'/>
<offset>16</offset>
<use f='glibc_src_2.29/iconv/iconvconfig.c' l='1158' u='m' c='write_output'/>
<use f='glibc_src_2.29/iconv/iconvconfig.c' l='1161' u='m' c='write_output'/>
<use f='glibc_src_2.29/iconv/iconvconfig.c' l='1163' u='m' c='write_output'/>
