<dec f='glibc_src_2.26/iconv/iconvconfig.h' l='59' type='struct extra_entry_module [0]'/>
<use f='glibc_src_2.26/iconv/gconv_cache.c' l='303' u='m' c='__gconv_lookup_cache'/>
<use f='glibc_src_2.26/iconv/gconv_cache.c' l='328' u='m' c='__gconv_lookup_cache'/>
<use f='glibc_src_2.26/iconv/gconv_cache.c' l='334' u='m' c='__gconv_lookup_cache'/>
<use f='glibc_src_2.26/iconv/gconv_cache.c' l='339' u='m' c='__gconv_lookup_cache'/>
<use f='glibc_src_2.26/iconv/gconv_cache.c' l='340' u='m' c='__gconv_lookup_cache'/>
<use f='glibc_src_2.26/iconv/gconv_cache.c' l='353' u='m' c='__gconv_lookup_cache'/>
<offset>16</offset>
<use f='glibc_src_2.26/iconv/iconvconfig.c' l='1159' u='m' c='write_output'/>
<use f='glibc_src_2.26/iconv/iconvconfig.c' l='1162' u='m' c='write_output'/>
<use f='glibc_src_2.26/iconv/iconvconfig.c' l='1164' u='m' c='write_output'/>
